#!/bin/bash
#
# ~/.bash_exports

# Set the default collation order.
export LC_COLLATE=C

# Set the default editor.
export EDITOR='vim'

# Prevent saving commands that begin with spaces and duplicates to the history
# list.
export HISTCONTROL=ignoreboth

# Prevent saving certain commands to the history list.
export HISTIGNORE='&:bg:fg'

# Set the maximum number of lines contained in the history file.
export HISTFILESIZE=1000

# Set the number of commands to remember in the command history.
export HISTSIZE=1000

# Prevent clearing the screen after quitting a manual page.
export MANPAGER='less --no-init'

# Make new shells get the history lines from all previous shells.
export PROMPT_COMMAND="history -a; ${PROMPT_COMMAND}"

# Make `less` more friendly for non-text input files.
if [[ -x /usr/bin/lesspipe ]]; then
  eval "$(SHELL=/bin/sh lesspipe)"
fi

# Enable 256-color terminal.
if [[ "${COLORTERM}" == gnome-* && "${TERM}" == xterm ]] && infocmp gnome-256color &> /dev/null; then
  export TERM=gnome-256color
elif infocmp xterm-256color &> /dev/null; then
  export TERM=xterm-256color
fi
