#!/bin/bash
#
# ~/.bash_options

# Make `cd` accept a variable name as an argument.
shopt -s cdable_vars

# Auto correct typos in path names when using `cd`.
shopt -s cdspell

# Auto refresh program location cache.
shopt -s checkhash

# Update the window size after each command.
shopt -s checkwinsize

# Save multi-line commands in the history as a single line.
shopt -s cmdhist

# Append the history list to file instead of overwriting.
shopt -s histappend

# Allow user to modify a history substitution.
shopt -s histreedit

# Allow user to review a history substitution result by loading the resulting
# line into the editing buffer.
shopt -s histverify

# Enable case-insensitive globbing.
shopt -s nocaseglob

# Disable empty completion.
shopt -s no_empty_cmd_completion

# Make `less` more friendly for non-text input files.
[[ -x '/usr/bin/lesspipe' ]] && eval "$(SHELL=/bin/sh lesspipe)"
