#!/bin/bash
#
# ~/.bash_functions

#######################################
# Lists all defined functions.
#######################################
list_functions() {
  declare -F | grep --invert-match '\-f _'
}

#######################################
# Creates new directories and enters the last one.
#######################################
mkd() {
  mkdir --parents --verbose -- "$@" && cd "$_" || exit 1
}

#######################################
# Searches for text within Bash history.
#######################################
qh() {
  grep --color=always -- "$*" "${HISTFILE}" | less -RX
}

#######################################
# Searches for text within the current directory.
#######################################
qt() {
  grep --color=always --ignore-case --recursive --exclude-dir={.git,node_modules} -- "$*" . | less -RX
}

#######################################
# Converts (CR)(LF) characters to (LF).
#######################################
crlf2lf() {
  cat "$@" <&0 | sed 's/\r$//g'
}

#######################################
# Converts (LF) characters to (CR)(LF).
#######################################
lf2crlf() {
  cat "$@" <&0 | sed 's/$/\r/g'
}

#######################################
# Shows a desktop notification when a command finishes.
#######################################
alert() {
  # shellcheck disable=SC2181
  local -r icon="$([[ $? -eq 0 ]] && echo terminal || echo error)"
  local -r summary="$(history | tail --lines=1 | sed 's/^\s*[0-9]*\s*//' | sed 's/;\s*alert\s*$//')"
  notify-send --urgency=low --icon="${icon}" "${summary}"
}
