#!/bin/bash
#
# ~/.bash_exports

# Set default locale to English (US).
export LANG='en_US.UTF-8'

# Set letter sorting as in C.
export LC_COLLATE='C'

# Make vim the default editor.
export EDITOR='vim'

# Prevent storing lines which begin with a space or match the last history line
# to the history list.
export HISTCONTROL='ignoreboth'

# Set the maximum number of lines to store in the history file.
export HISTFILESIZE=1000

# Set the maximum number of lines to remember in the command history.
export HISTSIZE=1000

# Prevent storing some commands to the history list.
export HISTIGNORE='&:bg:fg'

# Make history show the time for each command.
export HISTTIMEFORMAT='%F %T '

# Set the number of trailing directory components to retain in the prompt.
export PROMPT_DIRTRIM=3

# Make new shells get the history lines from all previous shells.
if [[ ! "${PROMPT_COMMAND}" =~ 'history -a;' ]]; then
  export PROMPT_COMMAND="history -a; ${PROMPT_COMMAND}"
fi

# Enable 256 color terminal.
if [[ "${COLORTERM}" == gnome-* && "${TERM}" == xterm ]] \
  && infocmp gnome-256color &> /dev/null; then
  export TERM='gnome-256color'
elif infocmp xterm-256color &> /dev/null; then
  export TERM='xterm-256color'
fi
