#!/bin/bash
#
# ~/.bash_prompt

#######################################
# Gets the Git repository details.
#######################################
prompt_git() {
  local branch_name
  local status

  # Check if the current directory is in a Git repository.
  if [[ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" != 'true' ]]; then
    return
  fi
  # Check if the current directory is in `.git`.
  if [[ "$(git rev-parse --is-inside-git-dir 2> /dev/null)" == 'true' ]]; then
    return
  fi

  # Ensure index is up-to-date.
  git update-index --really-refresh -q &> /dev/null

  # Check for uncommitted changes.
  if ! git diff --quiet --ignore-submodules --cached; then
    status="${status}+"
  fi
  # Check for unstaged changes.
  if ! git diff-files --quiet --ignore-submodules --; then
    status="${status}!"
  fi
  # Check for untracked files.
  if [[ -n "$(git ls-files --others --exclude-standard)" ]]; then
    status="${status}?"
  fi
  # Check for stashed files.
  if git rev-parse --verify refs/stash &> /dev/null; then
    status="${status}$"
  fi

  if [[ -n "${status}" ]]; then
    status=" ${status}"
  fi

  # Get the branch name or short commit SHA.
  branch_name="$(git symbolic-ref --quiet --short HEAD 2> /dev/null ||
    git rev-parse --short HEAD 2> /dev/null ||
    printf '(unknown)')"

  printf '%s[%s%s]%s' "${1}" "${branch_name}" "${status}" "${2}"
}

#######################################
# Sets up the Bash prompts.
# shellcheck disable=SC2034
#######################################
set_prompts() {
  local -r reset='\[\033[0m\]'
  local -r black='\[\033[1;30m\]'
  local -r red='\[\033[1;31m\]'
  local -r green='\[\033[1;32m\]'
  local -r yellow='\[\033[1;33m\]'
  local -r blue='\[\033[1;34m\]'
  local -r magenta='\[\033[1;35m\]'
  local -r cyan='\[\033[1;36m\]'
  local -r white='\[\033[1;37m\]'

  # Set the terminal title.
  #   user@hostname: ~
  PS1='\[\033]0;\u@\h: \w\007\]'

  # Set the default interactive prompt.
  #   user@hostname: ~ [master +!?$]
  #   $ ...
  PS1+=$'\n'
  PS1+="${green}\u@\h"
  PS1+="${black}: "
  PS1+="${blue}\w"
  PS1+="\$(prompt_git \" ${magenta}\" \"${reset}\")"
  PS1+=$'\n'
  PS1+="${black}\\$ "
  PS1+="${reset}"

  # Set the continuation interactive prompt.
  #   > ...
  PS2="${black}> ${reset}"

  export PS1
  export PS2
}

set_prompts
unset -f set_prompts
