#!/bin/bash
#
# ~/.bash_paths

#######################################
# Tests if a directory can be added into PATH.
#######################################
test_path() {
  if [[ -d "${1}" ]] && [[ ":${PATH}:" != *":${1}:"* ]]; then
    return 0
  fi
  return 1
}

#######################################
# Sets up the PATH environment variable.
#######################################
set_path() {
  local -r -a prepend_paths=(
    /usr/local/bin
  )
  local -r -a append_paths=(
    /usr/bin
    "${HOME}/bin"
    "${HOME}/.local/bin"
  )

  for index in ${!prepend_paths[*]}; do
    if test_path "${prepend_paths[$index]}"; then
      PATH="${prepend_paths[$index]}:${PATH}"
    fi
  done

  for index in ${!append_paths[*]}; do
    if test_path "${append_paths[$index]}"; then
      PATH="${PATH}:${append_paths[$index]}"
    fi
  done

  export PATH
}

set_path
unset -f test_path
unset -f set_path
