#!/bin/bash
#
# ~/.bash_functions

#######################################
# Lists all defined functions.
#######################################
list_functions() {
  declare -F | grep -v '\-f _'
}

#######################################
# Creates new directories and then enters the last one.
# Arguments:
#   Directories to create.
# Returns:
#   0 on success, non-zero on error.
#######################################
mkd() {
  mkdir -p "$@" && cd "$_"
}

#######################################
# Converts text files with DOS line endings to Unix line endings.
# Arguments:
#   Files to convert.
# Inputs:
#   Reads text from stdin if no argument is given.
# Outputs:
#   Writes converted text to stdout.
#######################################
crlf2lf() {
  if [[ $# -eq 0 ]]; then
    cat <&0
  elif [[ $# -eq 1 ]]; then
    if [[ -f "${1}" ]] && [[ -r "${1}" ]]; then
      cat "${1}"
    else
      echo "${1}"
    fi
  else
    return 1
  fi | sed -e "s/$(printf '\r')//g"
}

#######################################
# Converts text files with Unix line endings to DOS line endings.
# Arguments:
#   Files to convert.
# Inputs:
#   Reads text from stdin if no argument is given.
# Outputs:
#   Writes converted text to stdout.
#######################################
lf2crlf() {
  if [[ $# -eq 0 ]]; then
    cat <&0
  elif [[ $# -eq 1 ]]; then
    if [[ -f "${1}" ]] && [[ -r "${1}" ]]; then
      cat "${1}"
    else
      echo "${1}"
    fi
  else
    return 1
  fi | sed -e "s/$/$(printf '\r')/g"
}

#######################################
# Runs `git pull` on every directory within the current directory.
#######################################
git-updateall() {
  find . \
    -maxdepth 1 \
    ! -path . \
    -type d \
    -print \
    -execdir git --git-dir={}/.git --work-tree="${PWD}/{}" pull \;
}
