#!/bin/bash
#
# ~/.bash_aliases

# Allow aliases to be with sudo.
alias sudo='sudo '

# Easier navigation.
alias ..='cd ..'
alias ...='cd ../..'
alias -- -='cd -'
alias ~='cd ~'

# List directory contents.
alias la='ls -A --group-directories-first'
alias ll='ls -lah --group-directories-first --time-style=iso'

# Clear the screen like Windows.
alias cls='clear'
