#!/bin/bash
#
# ~/.inputrc

# Use case-insensitive tab autocompletion.
set completion-ignore-case on

# Auto list tab completions (use instead of TAB-cycling).
set show-all-if-ambiguous on

# Use the string that has already been typed as the prefix for searching through
# commands.
# Use Ctrl+P and Ctrl+N to walk through history the default way.
"\e[A": history-search-backward
"\e[B": history-search-forward

# Make Ctrl+Left and Ctrl+Right jump the cursor over words.
"\e[1;5C": forward-word
"\e[1;5D": backward-word
