#!/usr/bin/env bash
#
# Defines functions for `dotfiles clean`.

########################################
# Restores backup file if exists.
########################################
restore_file() {
  if [ -f "$1.bak" ]; then
    mv -fn "$1.bak" "$1"
  fi
}

########################################
# Removes a file if linked.
########################################
remove_link() {
  if [ -L "$1" ]; then
    rm -rf "$1"
  fi
}

########################################
# Removes linked dotfiles and restores their backup.
########################################
clean_dotfiles() {
  # Exit if dotfiles is not exist.
  if [ ! -d "$DOTFILES_PATH" ]; then
    die "Dotfiles not found."
  fi

  e_header "Clean Dotfiles"

  cd "$DOTFILES_PATH/src"

  for file in $(find . -type f | sed 's/^.\///' | sort -n); do
    remove_link "$HOME/$file" &&
    restore_file "$HOME/$file"

    if is_success; then
      e_success "$file"
    else
      e_error "$file"
    fi
  done
}
