#!/usr/bin/env bash
#
# Defines functions for `dotfiles help`.

########################################
# Prints help message.
########################################
e_help() {
cat <<EOT
Usage: $(basename "$0") <command>
Commands:
  help      Print help message
  list      List all dotfiles
  deploy    Link dotfiles to home directory
  init      Install software packages and setup environment settings
  update    Fetch latest dotfiles from the remote repository
  install   Install dotfiles (Run "update", "deploy" and "init" command)
  test      Test dotfiles and check shell scripts
  clean     Remove linked dotfiles and restore their backup
EOT
}
