#!/usr/bin/env bash
#
# Defines functions for `dotfiles update`.

########################################
# Fetches latest dotfiles from the remote repository.
########################################
update_dotfiles() {
  # Exit if dotfiles is not exist.
  if [ ! -d "$DOTFILES_PATH" ]; then
    die "Dotfiles not found."
  fi

  e_header "Update Dotfiles"

  cd "$DOTFILES_PATH"

  if ! is_exists "git"; then
    die "Git must be installed first."
  fi

  if ! is_git_repo "$DOTFILES_PATH"; then
    git init
    git remote add origin "$DOTFILES_GIT_URL"
  fi

  git reset --hard FETCH_HEAD
  git clean -fd
  git pull --rebase origin master
  git submodule update --recursive --init --quiet
}
